version: '3.8'

services:
  neo4j:
    image: neo4j:5.21.0-community
    container_name: neo4j_server
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/PWD_HERE
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    healthcheck:
      test: ["CMD-SHELL", "neo4j status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ckn-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ckn-network

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
      - neo4j
    ports:
      - "9092:9092"
    healthcheck:
      test: kafka-topics --bootstrap-server broker:9092 --list
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "oracle-events:1:1,oracle-alerts:1:1,oracle-aggregated:1:1,compiler-data:1:1,compiler-optimization:1:1,cameratraps-power-summary:1:1"
    networks:
      - ckn-network

  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: kafka-connect
    depends_on:
      - broker
      - neo4j
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker:29092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "compose-connect-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "docker-connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "docker-connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "docker-connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
    volumes:
      - ./ckn_broker:/app
    command: [ "sh", "-c", "/app/setup_connector.sh" ]
    networks:
      - ckn-network

  ckn-dashboard:
    image: iud2i/ckn-analytics-dashboard:latest
    container_name: dashboard
    ports:
      - "8502:8502"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PWD=PWD_HERE
      - OPENAI_API_KEY=''
      - PATRA_SERVER=''
    networks:
      - ckn-network

  oracle-alert-processor:
    image: iud2i/ckn-cameratraps-acc-alert:latest
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - CKN_BROKERS=broker:29092
      - ORACLE_ACC_CRITICAL_THRESHOLD=0.5
      - ORACLE_INPUT_TOPIC=oracle-events
      - ORACLE_ACC_ALERT_TOPIC=oracle-alerts
      - APP_ID=ckn-camera-traps-oracle-processor
    networks:
      - ckn-network

  oracle-aggr-processor:
    image: iud2i/ckn-cameratraps-agg:latest
    depends_on:
      broker:
        condition: service_healthy
    environment:
      - CKN_BROKERS=broker:29092
      - CKN_ORACLE_WINDOW_TIME=1
      - ORACLE_INPUT_TOPIC=oracle-events
      - ORACLE_AGG_ALERT_TOPIC=oracle-aggregated
      - APP_ID=ckn-camera-traps-oracle-aggreg
    networks:
      - ckn-network

networks:
  ckn-network:
    external: True